export const data = [
  {
    login: "piotrszymaniec",
    id: 5377285,
    node_id: "MDQ6VXNlcjUzNzcyODU=",
    avatar_url:
      "https://avatars.githubusercontent.com/u/5377285?u=9b78f49afe635a3d6ce29bb5b3972e10f9fa5fb0&v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/piotrszymaniec",
    html_url: "https://github.com/piotrszymaniec",
    followers_url: "https://api.github.com/users/piotrszymaniec/followers",
    following_url: "https://api.github.com/users/piotrszymaniec/following{/other_user}",
    gists_url: "https://api.github.com/users/piotrszymaniec/gists{/gist_id}",
    starred_url: "https://api.github.com/users/piotrszymaniec/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/piotrszymaniec/subscriptions",
    organizations_url: "https://api.github.com/users/piotrszymaniec/orgs",
    repos_url: "https://api.github.com/users/piotrszymaniec/repos",
    events_url: "https://api.github.com/users/piotrszymaniec/events{/privacy}",
    received_events_url: "https://api.github.com/users/piotrszymaniec/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "patrykomiotek",
    id: 5725623,
    node_id: "MDQ6VXNlcjU3MjU2MjM=",
    avatar_url: "https://avatars.githubusercontent.com/u/5725623?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/patrykomiotek",
    html_url: "https://github.com/patrykomiotek",
    followers_url: "https://api.github.com/users/patrykomiotek/followers",
    following_url: "https://api.github.com/users/patrykomiotek/following{/other_user}",
    gists_url: "https://api.github.com/users/patrykomiotek/gists{/gist_id}",
    starred_url: "https://api.github.com/users/patrykomiotek/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/patrykomiotek/subscriptions",
    organizations_url: "https://api.github.com/users/patrykomiotek/orgs",
    repos_url: "https://api.github.com/users/patrykomiotek/repos",
    events_url: "https://api.github.com/users/patrykomiotek/events{/privacy}",
    received_events_url: "https://api.github.com/users/patrykomiotek/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "SAK74",
    id: 7999796,
    node_id: "MDQ6VXNlcjc5OTk3OTY=",
    avatar_url:
      "https://avatars.githubusercontent.com/u/7999796?u=9cf229dc408d75c1703c0a5622cbf7cef7f3ce16&v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/SAK74",
    html_url: "https://github.com/SAK74",
    followers_url: "https://api.github.com/users/SAK74/followers",
    following_url: "https://api.github.com/users/SAK74/following{/other_user}",
    gists_url: "https://api.github.com/users/SAK74/gists{/gist_id}",
    starred_url: "https://api.github.com/users/SAK74/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/SAK74/subscriptions",
    organizations_url: "https://api.github.com/users/SAK74/orgs",
    repos_url: "https://api.github.com/users/SAK74/repos",
    events_url: "https://api.github.com/users/SAK74/events{/privacy}",
    received_events_url: "https://api.github.com/users/SAK74/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "bartassmo",
    id: 20480633,
    node_id: "MDQ6VXNlcjIwNDgwNjMz",
    avatar_url: "https://avatars.githubusercontent.com/u/20480633?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bartassmo",
    html_url: "https://github.com/bartassmo",
    followers_url: "https://api.github.com/users/bartassmo/followers",
    following_url: "https://api.github.com/users/bartassmo/following{/other_user}",
    gists_url: "https://api.github.com/users/bartassmo/gists{/gist_id}",
    starred_url: "https://api.github.com/users/bartassmo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/bartassmo/subscriptions",
    organizations_url: "https://api.github.com/users/bartassmo/orgs",
    repos_url: "https://api.github.com/users/bartassmo/repos",
    events_url: "https://api.github.com/users/bartassmo/events{/privacy}",
    received_events_url: "https://api.github.com/users/bartassmo/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "pamelaszymaniec",
    id: 22168437,
    node_id: "MDQ6VXNlcjIyMTY4NDM3",
    avatar_url:
      "https://avatars.githubusercontent.com/u/22168437?u=03b4e1300ad67eb36721dd33ccd1398291031e7f&v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/pamelaszymaniec",
    html_url: "https://github.com/pamelaszymaniec",
    followers_url: "https://api.github.com/users/pamelaszymaniec/followers",
    following_url: "https://api.github.com/users/pamelaszymaniec/following{/other_user}",
    gists_url: "https://api.github.com/users/pamelaszymaniec/gists{/gist_id}",
    starred_url: "https://api.github.com/users/pamelaszymaniec/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/pamelaszymaniec/subscriptions",
    organizations_url: "https://api.github.com/users/pamelaszymaniec/orgs",
    repos_url: "https://api.github.com/users/pamelaszymaniec/repos",
    events_url: "https://api.github.com/users/pamelaszymaniec/events{/privacy}",
    received_events_url: "https://api.github.com/users/pamelaszymaniec/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Misiorny",
    id: 27268030,
    node_id: "MDQ6VXNlcjI3MjY4MDMw",
    avatar_url:
      "https://avatars.githubusercontent.com/u/27268030?u=e3ecaec2c7a8219b64f5d24532b4b4795664f6a3&v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Misiorny",
    html_url: "https://github.com/Misiorny",
    followers_url: "https://api.github.com/users/Misiorny/followers",
    following_url: "https://api.github.com/users/Misiorny/following{/other_user}",
    gists_url: "https://api.github.com/users/Misiorny/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Misiorny/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Misiorny/subscriptions",
    organizations_url: "https://api.github.com/users/Misiorny/orgs",
    repos_url: "https://api.github.com/users/Misiorny/repos",
    events_url: "https://api.github.com/users/Misiorny/events{/privacy}",
    received_events_url: "https://api.github.com/users/Misiorny/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "olaftarlowski",
    id: 37384018,
    node_id: "MDQ6VXNlcjM3Mzg0MDE4",
    avatar_url: "https://avatars.githubusercontent.com/u/37384018?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/olaftarlowski",
    html_url: "https://github.com/olaftarlowski",
    followers_url: "https://api.github.com/users/olaftarlowski/followers",
    following_url: "https://api.github.com/users/olaftarlowski/following{/other_user}",
    gists_url: "https://api.github.com/users/olaftarlowski/gists{/gist_id}",
    starred_url: "https://api.github.com/users/olaftarlowski/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/olaftarlowski/subscriptions",
    organizations_url: "https://api.github.com/users/olaftarlowski/orgs",
    repos_url: "https://api.github.com/users/olaftarlowski/repos",
    events_url: "https://api.github.com/users/olaftarlowski/events{/privacy}",
    received_events_url: "https://api.github.com/users/olaftarlowski/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Margaretka15",
    id: 61712532,
    node_id: "MDQ6VXNlcjYxNzEyNTMy",
    avatar_url: "https://avatars.githubusercontent.com/u/61712532?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Margaretka15",
    html_url: "https://github.com/Margaretka15",
    followers_url: "https://api.github.com/users/Margaretka15/followers",
    following_url: "https://api.github.com/users/Margaretka15/following{/other_user}",
    gists_url: "https://api.github.com/users/Margaretka15/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Margaretka15/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Margaretka15/subscriptions",
    organizations_url: "https://api.github.com/users/Margaretka15/orgs",
    repos_url: "https://api.github.com/users/Margaretka15/repos",
    events_url: "https://api.github.com/users/Margaretka15/events{/privacy}",
    received_events_url: "https://api.github.com/users/Margaretka15/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Pasniczy",
    id: 72109970,
    node_id: "MDQ6VXNlcjcyMTA5OTcw",
    avatar_url:
      "https://avatars.githubusercontent.com/u/72109970?u=fc6590f286e13b269fc3c78a16e94db71270b706&v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Pasniczy",
    html_url: "https://github.com/Pasniczy",
    followers_url: "https://api.github.com/users/Pasniczy/followers",
    following_url: "https://api.github.com/users/Pasniczy/following{/other_user}",
    gists_url: "https://api.github.com/users/Pasniczy/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Pasniczy/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Pasniczy/subscriptions",
    organizations_url: "https://api.github.com/users/Pasniczy/orgs",
    repos_url: "https://api.github.com/users/Pasniczy/repos",
    events_url: "https://api.github.com/users/Pasniczy/events{/privacy}",
    received_events_url: "https://api.github.com/users/Pasniczy/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "MsAgnieszka",
    id: 90423224,
    node_id: "MDQ6VXNlcjkwNDIzMjI0",
    avatar_url:
      "https://avatars.githubusercontent.com/u/90423224?u=5092bd06edbbbb376bbd2d0a47c3567449de113a&v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MsAgnieszka",
    html_url: "https://github.com/MsAgnieszka",
    followers_url: "https://api.github.com/users/MsAgnieszka/followers",
    following_url: "https://api.github.com/users/MsAgnieszka/following{/other_user}",
    gists_url: "https://api.github.com/users/MsAgnieszka/gists{/gist_id}",
    starred_url: "https://api.github.com/users/MsAgnieszka/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/MsAgnieszka/subscriptions",
    organizations_url: "https://api.github.com/users/MsAgnieszka/orgs",
    repos_url: "https://api.github.com/users/MsAgnieszka/repos",
    events_url: "https://api.github.com/users/MsAgnieszka/events{/privacy}",
    received_events_url: "https://api.github.com/users/MsAgnieszka/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Ce-Wu",
    id: 95869457,
    node_id: "U_kgDOBbbaEQ",
    avatar_url: "https://avatars.githubusercontent.com/u/95869457?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Ce-Wu",
    html_url: "https://github.com/Ce-Wu",
    followers_url: "https://api.github.com/users/Ce-Wu/followers",
    following_url: "https://api.github.com/users/Ce-Wu/following{/other_user}",
    gists_url: "https://api.github.com/users/Ce-Wu/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Ce-Wu/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Ce-Wu/subscriptions",
    organizations_url: "https://api.github.com/users/Ce-Wu/orgs",
    repos_url: "https://api.github.com/users/Ce-Wu/repos",
    events_url: "https://api.github.com/users/Ce-Wu/events{/privacy}",
    received_events_url: "https://api.github.com/users/Ce-Wu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "aleksander-mrozek",
    id: 100879231,
    node_id: "U_kgDOBgNLfw",
    avatar_url:
      "https://avatars.githubusercontent.com/u/100879231?u=2054b7dd435e516d387fc1777e2212ba2e3c79c1&v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/aleksander-mrozek",
    html_url: "https://github.com/aleksander-mrozek",
    followers_url: "https://api.github.com/users/aleksander-mrozek/followers",
    following_url: "https://api.github.com/users/aleksander-mrozek/following{/other_user}",
    gists_url: "https://api.github.com/users/aleksander-mrozek/gists{/gist_id}",
    starred_url: "https://api.github.com/users/aleksander-mrozek/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/aleksander-mrozek/subscriptions",
    organizations_url: "https://api.github.com/users/aleksander-mrozek/orgs",
    repos_url: "https://api.github.com/users/aleksander-mrozek/repos",
    events_url: "https://api.github.com/users/aleksander-mrozek/events{/privacy}",
    received_events_url: "https://api.github.com/users/aleksander-mrozek/received_events",
    type: "User",
    site_admin: false,
  },
];
